### ISSUE TITLE
sIt1: t-SNE plot of all scientists (4 steps)

### ISSUE THREAD

**Issue by lazlostrange** [mslehre/text-embedding#26]

**Comment by MarioStanke** [comment]
function to store embeddings
input:
 - foldername
 - n number of files, named 0.txt, 1.txt, ...., (n-1).txt  (subset may be missing)
output:
 - a hdf5 file is stored as array with n rows and "embedding units" columns
 -  missing texts result in columns with only None entries

function to read embeddings and make the plot
 -
